export const orders = [
  {
    id: "DH001",
    customer: "Nguyễn Hoàng Văn A",
    name: "Áo thun Nam mùa hè năng động",
    status: "Đã tạo",
    checkout: "Chưa thanh toán",
    channel: "Shopee", 
    total: "1111111",
    createdAt: "01/01/2022 10:10 AM",
  },
  {
    id: "DH002",
    customer: "Hahahaha",
    name: "Áo khoác nữ",
    status: "Đóng gói",
    checkout: "Đã thanh toán",
    channel: "Lazada", 
    total: "2222222",
    createdAt: "02/02/2022 02:02 PM",
  },
  {
    id: "DH003",
    customer: "C",
    name: "Áo khoác mùa đông",
    status: "Đang giao",
    checkout: "Thanh toán một phần",
    channel: "Shopee", 
    total: "500000",
    createdAt: "03/03/2022 03:03 PM",
  },

  // 30 dòng dữ liệu bổ sung
  {
    id: "DH004",
    customer: "Trần Thị Bích",
    name: "Váy đầm công sở cao cấp",
    status: "Hoàn thành",
    checkout: "Đã thanh toán",
    channel: "Website", 
    total: "1850000",
    createdAt: "05/03/2022 09:30 AM",
  },
  {
    id: "DH005",
    customer: "Lê Minh Quân",
    name: "Giày thể thao Nam Pro Run",
    status: "Đang giao",
    checkout: "Chưa thanh toán",
    channel: "Tiki", 
    total: "899000",
    createdAt: "06/03/2022 11:45 AM",
  },
  {
    id: "DH006",
    customer: "Phạm Thu Trang",
    name: "Túi xách da thời trang",
    status: "Đóng gói",
    checkout: "Đã thanh toán",
    channel: "Lazada", 
    total: "450000",
    createdAt: "07/03/2022 01:20 PM",
  },
  {
    id: "DH007",
    customer: "Vũ Đình Kha",
    name: "Quần Jeans Slimfit",
    status: "Đã tạo",
    checkout: "Thanh toán một phần",
    channel: "Shopee", 
    total: "399000",
    createdAt: "08/03/2022 04:00 PM",
  },
  {
    id: "DH008",
    customer: "Đinh Phương Mai",
    name: "Áo sơ mi lụa tơ tằm",
    status: "Hủy",
    checkout: "Hoàn tiền",
    channel: "Website", 
    total: "620000",
    createdAt: "09/03/2022 08:15 AM",
  },
  {
    id: "DH009",
    customer: "Nguyễn Văn Đức",
    name: "Mũ lưỡi trai phong cách Hàn Quốc",
    status: "Hoàn thành",
    checkout: "Đã thanh toán",
    channel: "Tiki", 
    total: "150000",
    createdAt: "10/03/2022 10:55 AM",
  },
  {
    id: "DH010",
    customer: "Bùi Ngọc Ánh",
    name: "Set đồ bơi 2 mảnh",
    status: "Đang giao",
    checkout: "Chưa thanh toán",
    channel: "Lazada", 
    total: "780000",
    createdAt: "11/03/2022 03:30 PM",
  },
  {
    id: "DH011",
    customer: "Hồ Văn Tài",
    name: "Phụ kiện điện thoại",
    status: "Đóng gói",
    checkout: "Đã thanh toán",
    channel: "Shopee", 
    total: "95000",
    createdAt: "12/03/2022 06:40 PM",
  },
  {
    id: "DH012",
    customer: "Tô Mỹ Lệ",
    name: "Đồ gia dụng thông minh",
    status: "Đã tạo",
    checkout: "Thanh toán một phần",
    channel: "Website", 
    total: "2500000",
    createdAt: "13/03/2022 10:00 AM",
  },
  {
    id: "DH013",
    customer: "Đào Quang Anh",
    name: "Balo du lịch chống nước",
    status: "Hoàn thành",
    checkout: "Đã thanh toán",
    channel: "Tiki", 
    total: "550000",
    createdAt: "14/03/2022 01:15 PM",
  },
  {
    id: "DH014",
    customer: "Cao Thúy Vân",
    name: "Áo len cổ lọ Thu Đông",
    status: "Đang giao",
    checkout: "Chưa thanh toán",
    channel: "Lazada", 
    total: "420000",
    createdAt: "15/03/2022 05:00 PM",
  },
  {
    id: "DH015",
    customer: "Mai Thế Lực",
    name: "Tai nghe Bluetooth",
    status: "Đóng gói",
    checkout: "Đã thanh toán",
    channel: "Shopee", 
    total: "680000",
    createdAt: "16/03/2022 07:30 AM",
  },
  {
    id: "DH016",
    customer: "Ngô Thanh Thảo",
    name: "Bộ chăn ga gối đệm",
    status: "Đã tạo",
    checkout: "Thanh toán một phần",
    channel: "Website", 
    total: "3200000",
    createdAt: "17/03/2022 09:10 AM",
  },
  {
    id: "DH017",
    customer: "Phan Văn Nam",
    name: "Sách: Phát triển bản thân",
    status: "Hoàn thành",
    checkout: "Đã thanh toán",
    channel: "Tiki", 
    total: "125000",
    createdAt: "18/03/2022 11:50 AM",
  },
  {
    id: "DH018",
    customer: "Kiều Thị Loan",
    name: "Kem chống nắng Hàn Quốc",
    status: "Đang giao",
    checkout: "Chưa thanh toán",
    channel: "Lazada", 
    total: "350000",
    createdAt: "19/03/2022 02:25 PM",
  },
  {
    id: "DH019",
    customer: "Dương Tuấn Hùng",
    name: "Đồng hồ thông minh",
    status: "Đóng gói",
    checkout: "Đã thanh toán",
    channel: "Shopee", 
    total: "1250000",
    createdAt: "20/03/2022 05:40 PM",
  },
  {
    id: "DH020",
    customer: "Hoàng Tố Uyên",
    name: "Thảm yoga cao cấp",
    status: "Đã tạo",
    checkout: "Thanh toán một phần",
    channel: "Website", 
    total: "499000",
    createdAt: "21/03/2022 08:00 AM",
  },
  {
    id: "DH021",
    customer: "Nguyễn Nhật Minh",
    name: "Kính mát Unisex",
    status: "Hủy",
    checkout: "Hoàn tiền",
    channel: "Tiki", 
    total: "220000",
    createdAt: "22/03/2022 10:10 AM",
  },
  {
    id: "DH022",
    customer: "Trần Mai Hương",
    name: "Khăn choàng cashmere",
    status: "Hoàn thành",
    checkout: "Đã thanh toán",
    channel: "Lazada", 
    total: "280000",
    createdAt: "23/03/2022 12:45 PM",
  },
  {
    id: "DH023",
    customer: "Lê Hữu Nghĩa",
    name: "Ốp lưng điện thoại iPhone 13",
    status: "Đang giao",
    checkout: "Chưa thanh toán",
    channel: "Shopee", 
    total: "75000",
    createdAt: "24/03/2022 03:15 PM",
  },
  {
    id: "DH024",
    customer: "Phạm Hải Yến",
    name: "Bột ngũ cốc dinh dưỡng",
    status: "Đóng gói",
    checkout: "Đã thanh toán",
    channel: "Website", 
    total: "400000",
    createdAt: "25/03/2022 05:30 PM",
  },
  {
    id: "DH025",
    customer: "Vũ Thanh Tùng",
    name: "Đèn bàn LED chống cận",
    status: "Đã tạo",
    checkout: "Thanh toán một phần",
    channel: "Tiki", 
    total: "850000",
    createdAt: "26/03/2022 08:20 AM",
  },
  {
    id: "DH026",
    customer: "Đinh Xuân Lộc",
    name: "Cây cảnh mini để bàn",
    status: "Hoàn thành",
    checkout: "Đã thanh toán",
    channel: "Lazada", 
    total: "199000",
    createdAt: "27/03/2022 11:00 AM",
  },
  {
    id: "DH027",
    customer: "Nguyễn Hữu Trí",
    name: "Ghế gaming cao cấp",
    status: "Đang giao",
    checkout: "Chưa thanh toán",
    channel: "Shopee", 
    total: "4500000",
    createdAt: "28/03/2022 01:50 PM",
  },
  {
    id: "DH028",
    customer: "Bùi Thị Tuyết",
    name: "Nước hoa nữ Chanel",
    status: "Đóng gói",
    checkout: "Đã thanh toán",
    channel: "Website", 
    total: "2100000",
    createdAt: "29/03/2022 04:30 PM",
  },
  {
    id: "DH029",
    customer: "Hồ Kim Ngân",
    name: "Máy xay sinh tố đa năng",
    status: "Đã tạo",
    checkout: "Thanh toán một phần",
    channel: "Tiki", 
    total: "980000",
    createdAt: "30/03/2022 07:10 PM",
  },
  {
    id: "DH030",
    customer: "Tô Văn Quyết",
    name: "Combo chăm sóc da mặt",
    status: "Hoàn thành",
    checkout: "Đã thanh toán",
    channel: "Lazada", 
    total: "750000",
    createdAt: "31/03/2022 09:55 AM",
  },
  {
    id: "DH031",
    customer: "Đào Lan Hương",
    name: "Bút cảm ứng cho iPad",
    status: "Đang giao",
    checkout: "Chưa thanh toán",
    channel: "Shopee", 
    total: "599000",
    createdAt: "01/04/2022 01:00 PM",
  },
  {
    id: "DH032",
    customer: "Cao Xuân Tùng",
    name: "Đĩa CD nhạc Trịnh",
    status: "Đóng gói",
    checkout: "Đã thanh toán",
    channel: "Website", 
    total: "180000",
    createdAt: "02/04/2022 04:20 PM",
  },
  {
    id: "DH033",
    customer: "Mai Hoàng Uyên",
    name: "Gấu bông lớn",
    status: "Đã tạo",
    checkout: "Thanh toán một phần",
    channel: "Tiki", 
    total: "390000",
    createdAt: "03/04/2022 08:30 AM",
  },
];